#!/bin/bash

CAPACITY=$(cat /sys/class/power_supply/BAT0/capacity)
[ $CAPACITY -ge 0 ] && CHARGE=
[ $CAPACITY -ge 25 ] && CHARGE=
[ $CAPACITY -ge 50 ] && CHARGE=
[ $CAPACITY -ge 75 ] && CHARGE=
[ $CAPACITY -ge 90 ] && CHARGE=

UPOWER=$(cat /sys/class/power_supply/BAT0/status) 
[ "$UPOWER" = "Charging" ] || [ "$UPOWER" = "Fully-charged" ] && CHARGE=
BATTERY="$CHARGE   $CAPACITY%"    

echo "$BATTERY"
